name: Validate
on: [push]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate Scrapy code
        uses: jpetrucciani/black-check@master
        with:
          path: 'scrapy'
